HW_INIT_ONLY :=1
CFG_APWDT_DISABLE :=1

CFG_BATTERY_DETECT :=0
CFG_EMERGENCY_DL_SUPPORT :=0
CFG_RAM_CONSOLE :=0
CFG_UART_TOOL_HANDSHAKE :=0
CFG_USB_TOOL_HANDSHAKE :=0

CFG_LOAD_AP_ROM :=0
CFG_LOAD_CONN_SYS :=1

CFG_ATF_SUPPORT :=0
