CFG_APWDT_DISABLE :=1

CFG_BATTERY_DETECT :=0
CFG_EMERGENCY_DL_SUPPORT :=0
CFG_RAM_CONSOLE :=0

CFG_LOAD_MD_ROM :=1
CFG_LOAD_MD_RAMDISK :=1
CFG_LOAD_AP_ROM :=1
CFG_LOAD_MD_DSP :=1
CFG_LOAD_UBOOT :=0

CFG_ATF_SUPPORT :=0
