CFG_APWDT_DISABLE :=1

CFG_BATTERY_DETECT :=0
CFG_EMERGENCY_DL_SUPPORT :=0
CFG_RAM_CONSOLE :=0
CFG_UART_TOOL_HANDSHAKE :=0
CFG_USB_TOOL_HANDSHAKE :=1

CFG_LOAD_SLT_AARCH64_KERNEL:=1
CFG_LOAD_SLT_MD_RAMDISK :=1
CFG_LOAD_SLT_MD_DSP :=1
CFG_LOAD_SLT_MD :=1
CFG_LOAD_SLT_MD32 :=1
CFG_LOAD_AP_ROM :=1
CFG_LOAD_UBOOT :=0
CFG_LOAD_CONN_SYS :=0

SLT_VMIN := 0
SLT_VMAX := 0

CFG_ATF_SUPPORT :=0

