/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 */
/* MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */

/********************************************************************************************
 *     LEGAL DISCLAIMER
 *
 *     (Header of MediaTek Software/Firmware Release or Documentation)
 *
 *     BY OPENING OR USING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 *     THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE") RECEIVED
 *     FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON AN "AS-IS" BASIS
 *     ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES, EXPRESS OR IMPLIED,
 *     INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR
 *     A PARTICULAR PURPOSE OR NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY
 *     WHATSOEVER WITH RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
 *     INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK
 *     ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
 *     NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S SPECIFICATION
 *     OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
 *
 *     BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE LIABILITY WITH
 *     RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE, AT MEDIATEK'S OPTION,
TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE
 *     FEES OR SERVICE CHARGE PAID BY BUYER TO MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 *     THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE WITH THE LAWS
 *     OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF LAWS PRINCIPLES.
 ************************************************************************************************/
#ifndef _CFG_ISP_TUNING_IDX_PREVIEW_H_
#define _CFG_ISP_TUNING_IDX_PREVIEW_H_

#include <mtkcam/metadata/client/mtk_metadata_tag.h>

#define PREVIEW_SCENE_MODE_CONFIG(sensor, scene)\
    IDX_MODE_Preview(sensor, scene, eIDX_ISO_100)\
    IdxSet<EIspProfile_Preview, sensor, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_100>::idx;\
    IDX_MODE_Preview(sensor, scene, eIDX_ISO_200)\
    IdxSet<EIspProfile_Preview, sensor, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_200>::idx;\
    IDX_MODE_Preview(sensor, scene, eIDX_ISO_400)\
    IdxSet<EIspProfile_Preview, sensor, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_400>::idx;\
    IDX_MODE_Preview(sensor, scene, eIDX_ISO_800)\
    IdxSet<EIspProfile_Preview, sensor, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_800>::idx;\
    IDX_MODE_Preview(sensor, scene, eIDX_ISO_1200)\
    IdxSet<EIspProfile_Preview, sensor, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1200>::idx;\
    IDX_MODE_Preview(sensor, scene, eIDX_ISO_1600)\
    IdxSet<EIspProfile_Preview, sensor, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1600>::idx;\
    IDX_MODE_Preview(sensor, scene, eIDX_ISO_2000)\
    IdxSet<EIspProfile_Preview, sensor, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2000>::idx;\
    IDX_MODE_Preview(sensor, scene, eIDX_ISO_2400)\
    IdxSet<EIspProfile_Preview, sensor, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2400>::idx;\
    IDX_MODE_Preview(sensor, scene, eIDX_ISO_2800)\
    IdxSet<EIspProfile_Preview, sensor, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2800>::idx;\
    IDX_MODE_Preview(sensor, scene, eIDX_ISO_3200)\
    IdxSet<EIspProfile_Preview, sensor, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_3200>::idx;\

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Preview> <Sensor Mode: Preview>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_DISABLED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Preview( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_100 )
IDX_SET( OBC:0, BPC:0, NR1:0, CFA:0, GGM:0, ANR:0, CCR:0, EE:0, NR3D:0, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Preview( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_200 )
IDX_SET( OBC:0, BPC:1, NR1:1, CFA:1, GGM:0, ANR:1, CCR:1, EE:1, NR3D:1, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Preview( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_400 )
IDX_SET( OBC:0, BPC:1, NR1:1, CFA:2, GGM:0, ANR:2, CCR:2, EE:2, NR3D:2, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Preview( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_800 )
IDX_SET( OBC:1, BPC:2, NR1:2, CFA:3, GGM:0, ANR:3, CCR:3, EE:3, NR3D:3, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Preview( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1200 )
IDX_SET( OBC:1, BPC:2, NR1:2, CFA:4, GGM:0, ANR:4, CCR:4, EE:4, NR3D:4, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Preview( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1600 )
IDX_SET( OBC:1, BPC:2, NR1:2, CFA:5, GGM:0, ANR:5, CCR:5, EE:5, NR3D:5, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Preview( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2000 )
IDX_SET( OBC:1, BPC:2, NR1:2, CFA:6, GGM:0, ANR:6, CCR:6, EE:6, NR3D:6, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Preview( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2400 )
IDX_SET( OBC:1, BPC:2, NR1:2, CFA:7, GGM:0, ANR:7, CCR:7, EE:7, NR3D:7, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Preview( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2800 )
IDX_SET( OBC:1, BPC:2, NR1:2, CFA:8, GGM:0, ANR:8, CCR:8, EE:8, NR3D:8, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Preview( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_3200 )
IDX_SET( OBC:1, BPC:2, NR1:2, CFA:9, GGM:0, ANR:9, CCR:9, EE:9, NR3D:9, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_NORMAL)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_ACTION)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_NIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_THEATRE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_BEACH)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_SNOW)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_SUNSET)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_FIREWORKS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_SPORTS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_PARTY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_HDR)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_BARCODE)


//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Preview> <Sensor Mode: Capture>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_DISABLED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Preview( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_100 )
IDX_SET( OBC:2, BPC:3, NR1:3, CFA:10, GGM:0, ANR:10, CCR:0, EE:10, NR3D:10, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Preview( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_200 )
IDX_SET( OBC:2, BPC:4, NR1:4, CFA:11, GGM:0, ANR:11, CCR:1, EE:11, NR3D:11, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Preview( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_400 )
IDX_SET( OBC:2, BPC:4, NR1:4, CFA:12, GGM:0, ANR:12, CCR:2, EE:12, NR3D:12, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Preview( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_800 )
IDX_SET( OBC:3, BPC:5, NR1:5, CFA:13, GGM:0, ANR:13, CCR:3, EE:13, NR3D:13, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Preview( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1200 )
IDX_SET( OBC:3, BPC:5, NR1:5, CFA:14, GGM:0, ANR:14, CCR:4, EE:14, NR3D:14, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Preview( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1600 )
IDX_SET( OBC:3, BPC:5, NR1:5, CFA:15, GGM:0, ANR:15, CCR:5, EE:15, NR3D:15, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Preview( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2000 )
IDX_SET( OBC:3, BPC:5, NR1:5, CFA:16, GGM:0, ANR:16, CCR:6, EE:16, NR3D:16, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Preview( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2400 )
IDX_SET( OBC:3, BPC:5, NR1:5, CFA:17, GGM:0, ANR:17, CCR:7, EE:17, NR3D:17, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Preview( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2800 )
IDX_SET( OBC:3, BPC:5, NR1:5, CFA:18, GGM:0, ANR:18, CCR:8, EE:18, NR3D:18, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Preview( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_3200 )
IDX_SET( OBC:3, BPC:5, NR1:5, CFA:19, GGM:0, ANR:19, CCR:9, EE:19, NR3D:19, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_NORMAL)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_ACTION)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_NIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_THEATRE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_BEACH)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_SNOW)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_SUNSET)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_FIREWORKS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_SPORTS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_PARTY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_HDR)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_BARCODE)

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Preview> <Sensor Mode: Video>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_DISABLED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Preview( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_100 )
IDX_SET( OBC:4, BPC:6, NR1:6, CFA:20, GGM:0, ANR:20, CCR:0, EE:20, NR3D:20, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Preview( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_200 )
IDX_SET( OBC:4, BPC:7, NR1:7, CFA:21, GGM:0, ANR:21, CCR:1, EE:21, NR3D:21, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Preview( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_400 )
IDX_SET( OBC:4, BPC:7, NR1:7, CFA:22, GGM:0, ANR:22, CCR:2, EE:22, NR3D:22, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Preview( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_800 )
IDX_SET( OBC:5, BPC:8, NR1:8, CFA:23, GGM:0, ANR:23, CCR:3, EE:23, NR3D:23, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Preview( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1200 )
IDX_SET( OBC:5, BPC:8, NR1:8, CFA:24, GGM:0, ANR:24, CCR:4, EE:24, NR3D:24, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Preview( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1600 )
IDX_SET( OBC:5, BPC:8, NR1:8, CFA:25, GGM:0, ANR:25, CCR:5, EE:25, NR3D:25, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Preview( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2000 )
IDX_SET( OBC:5, BPC:8, NR1:8, CFA:26, GGM:0, ANR:26, CCR:6, EE:26, NR3D:26, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Preview( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2400 )
IDX_SET( OBC:5, BPC:8, NR1:8, CFA:27, GGM:0, ANR:27, CCR:7, EE:27, NR3D:27, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Preview( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2800 )
IDX_SET( OBC:5, BPC:8, NR1:8, CFA:28, GGM:0, ANR:28, CCR:8, EE:28, NR3D:28, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Preview( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_3200 )
IDX_SET( OBC:5, BPC:8, NR1:8, CFA:29, GGM:0, ANR:29, CCR:9, EE:29, NR3D:29, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_NORMAL)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_ACTION)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_NIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_THEATRE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_BEACH)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_SNOW)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_SUNSET)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_FIREWORKS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_SPORTS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_PARTY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_HDR)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_BARCODE)


//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Preview> <Sensor Mode: SlimVideo1>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_DISABLED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Preview( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_100 )
IDX_SET( OBC:6, BPC:9,  NR1:9,  CFA:30, GGM:0, ANR:30, CCR:0, EE:30, NR3D:30, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Preview( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_200 )
IDX_SET( OBC:6, BPC:10, NR1:10, CFA:31, GGM:0, ANR:31, CCR:1, EE:31, NR3D:31, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Preview( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_400 )
IDX_SET( OBC:6, BPC:10, NR1:10, CFA:32, GGM:0, ANR:32, CCR:2, EE:32, NR3D:32, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Preview( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_800 )
IDX_SET( OBC:7, BPC:11, NR1:11, CFA:33, GGM:0, ANR:33, CCR:3, EE:33, NR3D:33, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Preview( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1200 )
IDX_SET( OBC:7, BPC:11, NR1:11, CFA:34, GGM:0, ANR:34, CCR:4, EE:34, NR3D:34, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Preview( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1600 )
IDX_SET( OBC:7, BPC:11, NR1:11, CFA:35, GGM:0, ANR:35, CCR:5, EE:35, NR3D:35, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Preview( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2000 )
IDX_SET( OBC:7, BPC:11, NR1:11, CFA:36, GGM:0, ANR:36, CCR:6, EE:36, NR3D:36, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Preview( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2400 )
IDX_SET( OBC:7, BPC:11, NR1:11, CFA:37, GGM:0, ANR:37, CCR:7, EE:37, NR3D:37, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Preview( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2800 )
IDX_SET( OBC:7, BPC:11, NR1:11, CFA:38, GGM:0, ANR:38, CCR:8, EE:38, NR3D:38, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Preview( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_3200 )
IDX_SET( OBC:7, BPC:11, NR1:11, CFA:39, GGM:0, ANR:39, CCR:9, EE:39, NR3D:39, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_NORMAL)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_ACTION)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_NIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_THEATRE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_BEACH)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_SNOW)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_SUNSET)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_FIREWORKS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_SPORTS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_PARTY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_HDR)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_BARCODE)

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Preview> <Sensor Mode: SlimVideo2>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_DISABLED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Preview( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_100 )
IDX_SET( OBC:8, BPC:12, NR1:12, CFA:40, GGM:0, ANR:40, CCR:0, EE:40, NR3D:40, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Preview( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_200 )
IDX_SET( OBC:8, BPC:13, NR1:13, CFA:41, GGM:0, ANR:41, CCR:1, EE:41, NR3D:41, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Preview( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_400 )
IDX_SET( OBC:8, BPC:13, NR1:13, CFA:42, GGM:0, ANR:42, CCR:2, EE:42, NR3D:42, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Preview( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_800 )
IDX_SET( OBC:9, BPC:14, NR1:14, CFA:43, GGM:0, ANR:43, CCR:3, EE:43, NR3D:43, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Preview( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1200 )
IDX_SET( OBC:9, BPC:14, NR1:14, CFA:44, GGM:0, ANR:44, CCR:4, EE:44, NR3D:44, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Preview( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1600 )
IDX_SET( OBC:9, BPC:14, NR1:14, CFA:45, GGM:0, ANR:45, CCR:5, EE:45, NR3D:45, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Preview( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2000 )
IDX_SET( OBC:9, BPC:14, NR1:14, CFA:46, GGM:0, ANR:46, CCR:6, EE:46, NR3D:46, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Preview( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2400 )
IDX_SET( OBC:9, BPC:14, NR1:14, CFA:47, GGM:0, ANR:47, CCR:7, EE:47, NR3D:47, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Preview( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2800 )
IDX_SET( OBC:9, BPC:14, NR1:14, CFA:48, GGM:0, ANR:48, CCR:8, EE:48, NR3D:48, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Preview( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_3200 )
IDX_SET( OBC:9, BPC:14, NR1:14, CFA:49, GGM:0, ANR:49, CCR:9, EE:49, NR3D:49, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_NORMAL)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_ACTION)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_NIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_THEATRE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_BEACH)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_SNOW)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_SUNSET)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_FIREWORKS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_SPORTS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_PARTY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_HDR)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_BARCODE)

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Preview> <Sensor Mode: Custom1>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_DISABLED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Preview( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_100 )
IDX_SET( OBC:40, BPC:60, NR1:54, CFA:200, GGM:0, ANR:260, CCR:0, EE:220, NR3D:140, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Preview( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_200 )
IDX_SET( OBC:40, BPC:61, NR1:55, CFA:201, GGM:0, ANR:261, CCR:1, EE:221, NR3D:141, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Preview( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_400 )
IDX_SET( OBC:40, BPC:61, NR1:55, CFA:202, GGM:0, ANR:262, CCR:2, EE:222, NR3D:142, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Preview( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_800 )
IDX_SET( OBC:41, BPC:62, NR1:56, CFA:203, GGM:0, ANR:263, CCR:3, EE:223, NR3D:143, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Preview( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1200 )
IDX_SET( OBC:41, BPC:62, NR1:56, CFA:204, GGM:0, ANR:264, CCR:4, EE:224, NR3D:144, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Preview( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1600 )
IDX_SET( OBC:41, BPC:62, NR1:56, CFA:205, GGM:0, ANR:265, CCR:5, EE:225, NR3D:145, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Preview( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2000 )
IDX_SET( OBC:41, BPC:62, NR1:56, CFA:206, GGM:0, ANR:266, CCR:6, EE:226, NR3D:146, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Preview( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2400 )
IDX_SET( OBC:41, BPC:62, NR1:56, CFA:207, GGM:0, ANR:267, CCR:7, EE:227, NR3D:147, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Preview( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2800 )
IDX_SET( OBC:41, BPC:62, NR1:56, CFA:208, GGM:0, ANR:268, CCR:8, EE:228, NR3D:148, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Preview( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_3200 )
IDX_SET( OBC:41, BPC:62, NR1:56, CFA:209, GGM:0, ANR:269, CCR:9, EE:229, NR3D:149, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_NORMAL)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_ACTION)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_NIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_THEATRE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_BEACH)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_SNOW)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_SUNSET)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_FIREWORKS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_SPORTS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_PARTY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_HDR)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_BARCODE)

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Preview> <Sensor Mode: Custom2>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_DISABLED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Preview( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_100 )
IDX_SET( OBC:42, BPC:63, NR1:57, CFA:210, GGM:0, ANR:270, CCR:0, EE:230, NR3D:150, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Preview( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_200 )
IDX_SET( OBC:42, BPC:64, NR1:58, CFA:211, GGM:0, ANR:271, CCR:1, EE:231, NR3D:151, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Preview( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_400 )
IDX_SET( OBC:42, BPC:64, NR1:58, CFA:212, GGM:0, ANR:272, CCR:2, EE:232, NR3D:152, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Preview( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_800 )
IDX_SET( OBC:43, BPC:65, NR1:59, CFA:213, GGM:0, ANR:273, CCR:3, EE:233, NR3D:153, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Preview( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1200 )
IDX_SET( OBC:43, BPC:65, NR1:59, CFA:214, GGM:0, ANR:274, CCR:4, EE:234, NR3D:154, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Preview( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1600 )
IDX_SET( OBC:43, BPC:65, NR1:59, CFA:215, GGM:0, ANR:275, CCR:5, EE:235, NR3D:155, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Preview( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2000 )
IDX_SET( OBC:43, BPC:65, NR1:59, CFA:216, GGM:0, ANR:276, CCR:6, EE:236, NR3D:156, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Preview( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2400 )
IDX_SET( OBC:43, BPC:65, NR1:59, CFA:217, GGM:0, ANR:277, CCR:7, EE:237, NR3D:157, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Preview( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2800 )
IDX_SET( OBC:43, BPC:65, NR1:59, CFA:218, GGM:0, ANR:278, CCR:8, EE:238, NR3D:158, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Preview( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_3200 )
IDX_SET( OBC:43, BPC:65, NR1:59, CFA:219, GGM:0, ANR:279, CCR:9, EE:239, NR3D:159, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_NORMAL)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_ACTION)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_NIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_THEATRE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_BEACH)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_SNOW)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_SUNSET)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_FIREWORKS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_SPORTS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_PARTY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_HDR)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_BARCODE)

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Preview> <Sensor Mode: Custom3>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_DISABLED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Preview( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_100 )
IDX_SET( OBC:44, BPC:66, NR1:60, CFA:220, GGM:0, ANR:280, CCR:0, EE:240, NR3D:160, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Preview( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_200 )
IDX_SET( OBC:44, BPC:67, NR1:61, CFA:221, GGM:0, ANR:281, CCR:1, EE:241, NR3D:161, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Preview( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_400 )
IDX_SET( OBC:44, BPC:67, NR1:61, CFA:222, GGM:0, ANR:282, CCR:2, EE:242, NR3D:162, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Preview( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_800 )
IDX_SET( OBC:45, BPC:68, NR1:62, CFA:223, GGM:0, ANR:283, CCR:3, EE:243, NR3D:163, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Preview( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1200 )
IDX_SET( OBC:45, BPC:68, NR1:62, CFA:224, GGM:0, ANR:284, CCR:4, EE:244, NR3D:164, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Preview( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1600 )
IDX_SET( OBC:45, BPC:68, NR1:62, CFA:225, GGM:0, ANR:285, CCR:5, EE:245, NR3D:165, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Preview( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2000 )
IDX_SET( OBC:45, BPC:68, NR1:62, CFA:226, GGM:0, ANR:286, CCR:6, EE:246, NR3D:166, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Preview( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2400 )
IDX_SET( OBC:45, BPC:68, NR1:62, CFA:227, GGM:0, ANR:287, CCR:7, EE:247, NR3D:167, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Preview( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2800 )
IDX_SET( OBC:45, BPC:68, NR1:62, CFA:228, GGM:0, ANR:288, CCR:8, EE:248, NR3D:168, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Preview( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_3200 )
IDX_SET( OBC:45, BPC:68, NR1:62, CFA:229, GGM:0, ANR:289, CCR:9, EE:249, NR3D:169, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_NORMAL)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_ACTION)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_NIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_THEATRE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_BEACH)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_SNOW)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_SUNSET)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_FIREWORKS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_SPORTS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_PARTY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_HDR)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_BARCODE)

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Preview> <Sensor Mode: Custom4>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_DISABLED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Preview( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_100 )
IDX_SET( OBC:46, BPC:69, NR1:63, CFA:230, GGM:0, ANR:290, CCR:0, EE:250, NR3D:170, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Preview( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_200 )
IDX_SET( OBC:46, BPC:70, NR1:64, CFA:231, GGM:0, ANR:291, CCR:1, EE:251, NR3D:171, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Preview( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_400 )
IDX_SET( OBC:46, BPC:70, NR1:64, CFA:232, GGM:0, ANR:292, CCR:2, EE:252, NR3D:172, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Preview( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_800 )
IDX_SET( OBC:47, BPC:71, NR1:65, CFA:233, GGM:0, ANR:293, CCR:3, EE:253, NR3D:173, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Preview( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1200 )
IDX_SET( OBC:47, BPC:71, NR1:65, CFA:234, GGM:0, ANR:294, CCR:4, EE:254, NR3D:174, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Preview( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1600 )
IDX_SET( OBC:47, BPC:71, NR1:65, CFA:235, GGM:0, ANR:295, CCR:5, EE:255, NR3D:175, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Preview( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2000 )
IDX_SET( OBC:47, BPC:71, NR1:65, CFA:236, GGM:0, ANR:296, CCR:6, EE:256, NR3D:176, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Preview( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2400 )
IDX_SET( OBC:47, BPC:71, NR1:65, CFA:237, GGM:0, ANR:297, CCR:7, EE:257, NR3D:177, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Preview( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2800 )
IDX_SET( OBC:47, BPC:71, NR1:65, CFA:238, GGM:0, ANR:298, CCR:8, EE:258, NR3D:178, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Preview( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_3200 )
IDX_SET( OBC:47, BPC:71, NR1:65, CFA:239, GGM:0, ANR:299, CCR:9, EE:259, NR3D:179, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_NORMAL)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_ACTION)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_NIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_THEATRE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_BEACH)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_SNOW)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_SUNSET)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_FIREWORKS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_SPORTS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_PARTY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_HDR)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_BARCODE)

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Preview> <Sensor Mode: Custom5>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_DISABLED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Preview( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_100 )
IDX_SET( OBC:48, BPC:72, NR1:66, CFA:240, GGM:0, ANR:300, CCR:0, EE:260, NR3D:180, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Preview( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_200 )
IDX_SET( OBC:48, BPC:73, NR1:67, CFA:241, GGM:0, ANR:301, CCR:1, EE:261, NR3D:181, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Preview( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_400 )
IDX_SET( OBC:48, BPC:73, NR1:67, CFA:242, GGM:0, ANR:302, CCR:2, EE:262, NR3D:182, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Preview( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_800 )
IDX_SET( OBC:49, BPC:74, NR1:68, CFA:243, GGM:0, ANR:303, CCR:3, EE:263, NR3D:183, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Preview( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1200 )
IDX_SET( OBC:49, BPC:74, NR1:68, CFA:244, GGM:0, ANR:304, CCR:4, EE:264, NR3D:184, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Preview( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1600 )
IDX_SET( OBC:49, BPC:74, NR1:68, CFA:245, GGM:0, ANR:305, CCR:5, EE:265, NR3D:185, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Preview( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2000 )
IDX_SET( OBC:49, BPC:74, NR1:68, CFA:246, GGM:0, ANR:306, CCR:6, EE:266, NR3D:186, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Preview( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2400 )
IDX_SET( OBC:49, BPC:74, NR1:68, CFA:247, GGM:0, ANR:307, CCR:7, EE:267, NR3D:187, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Preview( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2800 )
IDX_SET( OBC:49, BPC:74, NR1:68, CFA:248, GGM:0, ANR:308, CCR:8, EE:268, NR3D:188, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Preview( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_3200 )
IDX_SET( OBC:49, BPC:74, NR1:68, CFA:249, GGM:0, ANR:309, CCR:9, EE:269, NR3D:189, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_NORMAL)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_ACTION)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_NIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_THEATRE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_BEACH)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_SNOW)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_SUNSET)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_FIREWORKS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_SPORTS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_PARTY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_HDR)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_BARCODE)

#endif //  _CFG_ISP_TUNING_IDX_PREVIEW_H_

