/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 */
/* MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */

/********************************************************************************************
 *     LEGAL DISCLAIMER
 *
 *     (Header of MediaTek Software/Firmware Release or Documentation)
 *
 *     BY OPENING OR USING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 *     THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE") RECEIVED
 *     FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON AN "AS-IS" BASIS
 *     ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES, EXPRESS OR IMPLIED,
 *     INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR
 *     A PARTICULAR PURPOSE OR NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY
 *     WHATSOEVER WITH RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
 *     INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK
 *     ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
 *     NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S SPECIFICATION
 *     OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
 *
 *     BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE LIABILITY WITH
 *     RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE, AT MEDIATEK'S OPTION,
TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE
 *     FEES OR SERVICE CHARGE PAID BY BUYER TO MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 *     THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE WITH THE LAWS
 *     OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF LAWS PRINCIPLES.
 ************************************************************************************************/
#ifndef _CFG_ISP_TUNING_IDX_CAPTURE_H_
#define _CFG_ISP_TUNING_IDX_CAPTURE_H_


#include <mtkcam/metadata/client/mtk_metadata_tag.h>

#define CAPTURE_SCENE_MODE_CONFIG(sensor, scene)\
    IDX_MODE_Capture(sensor, scene, eIDX_ISO_100)\
    IdxSet<EIspProfile_Capture, sensor, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_100>::idx;\
    IDX_MODE_Capture(sensor, scene, eIDX_ISO_200)\
    IdxSet<EIspProfile_Capture, sensor, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_200>::idx;\
    IDX_MODE_Capture(sensor, scene, eIDX_ISO_400)\
    IdxSet<EIspProfile_Capture, sensor, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_400>::idx;\
    IDX_MODE_Capture(sensor, scene, eIDX_ISO_800)\
    IdxSet<EIspProfile_Capture, sensor, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_800>::idx;\
    IDX_MODE_Capture(sensor, scene, eIDX_ISO_1200)\
    IdxSet<EIspProfile_Capture, sensor, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1200>::idx;\
    IDX_MODE_Capture(sensor, scene, eIDX_ISO_1600)\
    IdxSet<EIspProfile_Capture, sensor, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1600>::idx;\
    IDX_MODE_Capture(sensor, scene, eIDX_ISO_2000)\
    IdxSet<EIspProfile_Capture, sensor, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2000>::idx;\
    IDX_MODE_Capture(sensor, scene, eIDX_ISO_2400)\
    IdxSet<EIspProfile_Capture, sensor, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2400>::idx;\
    IDX_MODE_Capture(sensor, scene, eIDX_ISO_2800)\
    IdxSet<EIspProfile_Capture, sensor, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2800>::idx;\
    IDX_MODE_Capture(sensor, scene, eIDX_ISO_3200)\
    IdxSet<EIspProfile_Capture, sensor, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_3200>::idx;\

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Capture> <Sensor Mode: Preview>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_DISABLED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Capture( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_100 )
IDX_SET( OBC:20, BPC:30, NR1:30, CFA:100, GGM:0, ANR:100, CCR:0, EE:100, NR3D:0, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Capture( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_200 )
IDX_SET( OBC:20, BPC:31, NR1:31, CFA:101, GGM:0, ANR:101, CCR:1, EE:101, NR3D:0, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Capture( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_400 )
IDX_SET( OBC:20, BPC:31, NR1:31, CFA:102, GGM:0, ANR:102, CCR:2, EE:102, NR3D:0, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Capture( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_800 )
IDX_SET( OBC:21, BPC:32, NR1:32, CFA:103, GGM:0, ANR:103, CCR:3, EE:103, NR3D:0, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Capture( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1200 )
IDX_SET( OBC:21, BPC:32, NR1:32, CFA:104, GGM:0, ANR:104, CCR:4, EE:104, NR3D:0, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Capture( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1600 )
IDX_SET( OBC:21, BPC:32, NR1:32, CFA:105, GGM:0, ANR:105, CCR:5, EE:105, NR3D:0, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Capture( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2000 )
IDX_SET( OBC:21, BPC:32, NR1:32, CFA:106, GGM:0, ANR:106, CCR:6, EE:106, NR3D:0, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Capture( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2400 )
IDX_SET( OBC:21, BPC:32, NR1:32, CFA:107, GGM:0, ANR:107, CCR:7, EE:107, NR3D:0, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Capture( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2800 )
IDX_SET( OBC:21, BPC:32, NR1:32, CFA:108, GGM:0, ANR:108, CCR:8, EE:108, NR3D:0, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Capture( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_3200 )
IDX_SET( OBC:21, BPC:32, NR1:32, CFA:109, GGM:0, ANR:109, CCR:9, EE:109, NR3D:0, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_NORMAL)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_ACTION)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_NIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_THEATRE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_BEACH)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_SNOW)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_SUNSET)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_FIREWORKS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_SPORTS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_PARTY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_HDR)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_BARCODE)

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Capture> <Sensor Mode: Capture>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_DISABLED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Capture( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_100 )
IDX_SET( OBC:22, BPC:33, NR1:33, CFA:110, GGM:0, ANR:110, CCR:0, EE:110, NR3D:0, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Capture( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_200 )
IDX_SET( OBC:22, BPC:34, NR1:34, CFA:111, GGM:0, ANR:111, CCR:1, EE:111, NR3D:0, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Capture( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_400 )
IDX_SET( OBC:22, BPC:34, NR1:34, CFA:112, GGM:0, ANR:112, CCR:2, EE:112, NR3D:0, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Capture( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_800 )
IDX_SET( OBC:23, BPC:35, NR1:35, CFA:113, GGM:0, ANR:113, CCR:3, EE:113, NR3D:0, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Capture( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1200 )
IDX_SET( OBC:23, BPC:35, NR1:35, CFA:114, GGM:0, ANR:114, CCR:4, EE:114, NR3D:0, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Capture( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1600 )
IDX_SET( OBC:23, BPC:35, NR1:35, CFA:115, GGM:0, ANR:115, CCR:5, EE:115, NR3D:0, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Capture( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2000 )
IDX_SET( OBC:23, BPC:35, NR1:35, CFA:116, GGM:0, ANR:116, CCR:6, EE:116, NR3D:0, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Capture( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2400 )
IDX_SET( OBC:23, BPC:35, NR1:35, CFA:117, GGM:0, ANR:117, CCR:7, EE:117, NR3D:0, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Capture( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2800 )
IDX_SET( OBC:23, BPC:35, NR1:35, CFA:118, GGM:0, ANR:118, CCR:8, EE:118, NR3D:0, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Capture( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_3200 )
IDX_SET( OBC:23, BPC:35, NR1:35, CFA:119, GGM:0, ANR:119, CCR:9, EE:119, NR3D:0, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_NORMAL)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_ACTION)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_NIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_THEATRE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_BEACH)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_SNOW)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_SUNSET)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_FIREWORKS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_SPORTS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_PARTY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_HDR)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_BARCODE)


//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Capture> <Sensor Mode: Video>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_DISABLED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Capture( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_100 )
IDX_SET( OBC:24, BPC:36, NR1:36, CFA:120, GGM:0, ANR:120, CCR:0, EE:120, NR3D:0, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Capture( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_200 )
IDX_SET( OBC:24, BPC:37, NR1:37, CFA:121, GGM:0, ANR:121, CCR:1, EE:121, NR3D:0, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Capture( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_400 )
IDX_SET( OBC:24, BPC:37, NR1:37, CFA:122, GGM:0, ANR:122, CCR:2, EE:122, NR3D:0, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Capture( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_800 )
IDX_SET( OBC:25, BPC:38, NR1:38, CFA:123, GGM:0, ANR:123, CCR:3, EE:123, NR3D:0, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Capture( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1200 )
IDX_SET( OBC:25, BPC:38, NR1:38, CFA:124, GGM:0, ANR:124, CCR:4, EE:124, NR3D:0, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Capture( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1600 )
IDX_SET( OBC:25, BPC:38, NR1:38, CFA:125, GGM:0, ANR:125, CCR:5, EE:125, NR3D:0, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Capture( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2000 )
IDX_SET( OBC:25, BPC:38, NR1:38, CFA:126, GGM:0, ANR:126, CCR:6, EE:126, NR3D:0, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Capture( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2400 )
IDX_SET( OBC:25, BPC:38, NR1:38, CFA:127, GGM:0, ANR:127, CCR:7, EE:127, NR3D:0, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Capture( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2800 )
IDX_SET( OBC:25, BPC:38, NR1:38, CFA:128, GGM:0, ANR:128, CCR:8, EE:128, NR3D:0, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Capture( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_3200 )
IDX_SET( OBC:25, BPC:38, NR1:38, CFA:129, GGM:0, ANR:129, CCR:9, EE:129, NR3D:0, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_NORMAL)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_ACTION)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_NIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_THEATRE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_BEACH)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_SNOW)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_SUNSET)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_FIREWORKS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_SPORTS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_PARTY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_HDR)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_BARCODE)


//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Capture> <Sensor Mode: SlimVideo1>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_DISABLED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Capture( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_100 )
IDX_SET( OBC:26, BPC:39, NR1:39, CFA:130, GGM:0, ANR:130, CCR:0, EE:130, NR3D:0, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Capture( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_200 )
IDX_SET( OBC:26, BPC:40, NR1:40, CFA:131, GGM:0, ANR:131, CCR:1, EE:131, NR3D:0, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Capture( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_400 )
IDX_SET( OBC:26, BPC:40, NR1:40, CFA:132, GGM:0, ANR:132, CCR:2, EE:132, NR3D:0, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Capture( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_800 )
IDX_SET( OBC:27, BPC:41, NR1:41, CFA:133, GGM:0, ANR:133, CCR:3, EE:133, NR3D:0, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Capture( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1200 )
IDX_SET( OBC:27, BPC:41, NR1:41, CFA:134, GGM:0, ANR:134, CCR:4, EE:134, NR3D:0, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Capture( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1600 )
IDX_SET( OBC:27, BPC:41, NR1:41, CFA:135, GGM:0, ANR:135, CCR:5, EE:135, NR3D:0, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Capture( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2000 )
IDX_SET( OBC:27, BPC:41, NR1:41, CFA:136, GGM:0, ANR:136, CCR:6, EE:136, NR3D:0, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Capture( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2400 )
IDX_SET( OBC:27, BPC:41, NR1:41, CFA:137, GGM:0, ANR:137, CCR:7, EE:137, NR3D:0, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Capture( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2800 )
IDX_SET( OBC:27, BPC:41, NR1:41, CFA:138, GGM:0, ANR:138, CCR:8, EE:138, NR3D:0, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Capture( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_3200 )
IDX_SET( OBC:27, BPC:41, NR1:41, CFA:139, GGM:0, ANR:139, CCR:9, EE:139, NR3D:0, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_NORMAL)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_ACTION)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_NIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_THEATRE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_BEACH)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_SNOW)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_SUNSET)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_FIREWORKS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_SPORTS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_PARTY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_HDR)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_BARCODE)

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Capture> <Sensor Mode: SlimVideo2>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_DISABLED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Capture( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_100 )
IDX_SET( OBC:28, BPC:42, NR1:42, CFA:140, GGM:0, ANR:140, CCR:0, EE:140, NR3D:0, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Capture( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_200 )
IDX_SET( OBC:28, BPC:43, NR1:43, CFA:141, GGM:0, ANR:141, CCR:1, EE:141, NR3D:0, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Capture( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_400 )
IDX_SET( OBC:28, BPC:43, NR1:43, CFA:142, GGM:0, ANR:142, CCR:2, EE:142, NR3D:0, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Capture( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_800 )
IDX_SET( OBC:29, BPC:44, NR1:44, CFA:143, GGM:0, ANR:143, CCR:3, EE:143, NR3D:0, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Capture( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1200 )
IDX_SET( OBC:29, BPC:44, NR1:44, CFA:144, GGM:0, ANR:144, CCR:4, EE:144, NR3D:0, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Capture( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1600 )
IDX_SET( OBC:29, BPC:44, NR1:44, CFA:145, GGM:0, ANR:145, CCR:5, EE:145, NR3D:0, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Capture( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2000 )
IDX_SET( OBC:29, BPC:44, NR1:44, CFA:146, GGM:0, ANR:146, CCR:6, EE:146, NR3D:0, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Capture( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2400 )
IDX_SET( OBC:29, BPC:44, NR1:44, CFA:147, GGM:0, ANR:147, CCR:7, EE:147, NR3D:0, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Capture( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2800 )
IDX_SET( OBC:29, BPC:44, NR1:44, CFA:148, GGM:0, ANR:148, CCR:8, EE:148, NR3D:0, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Capture( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_3200 )
IDX_SET( OBC:29, BPC:44, NR1:44, CFA:149, GGM:0, ANR:149, CCR:9, EE:149, NR3D:0, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_NORMAL)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_ACTION)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_NIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_THEATRE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_BEACH)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_SNOW)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_SUNSET)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_FIREWORKS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_SPORTS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_PARTY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_HDR)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_BARCODE)

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Capture> <Sensor Mode: Custom1>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_DISABLED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Capture( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_100 )
IDX_SET( OBC:60, BPC:90, NR1:84, CFA:300, GGM:0, ANR:360, CCR:0, EE:320, NR3D:0, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Capture( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_200 )
IDX_SET( OBC:60, BPC:91, NR1:85, CFA:301, GGM:0, ANR:361, CCR:1, EE:321, NR3D:0, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Capture( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_400 )
IDX_SET( OBC:60, BPC:91, NR1:85, CFA:302, GGM:0, ANR:362, CCR:2, EE:322, NR3D:0, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Capture( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_800 )
IDX_SET( OBC:61, BPC:92, NR1:86, CFA:303, GGM:0, ANR:363, CCR:3, EE:323, NR3D:0, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Capture( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1200 )
IDX_SET( OBC:61, BPC:92, NR1:86, CFA:304, GGM:0, ANR:364, CCR:4, EE:324, NR3D:0, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Capture( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1600 )
IDX_SET( OBC:61, BPC:92, NR1:86, CFA:305, GGM:0, ANR:365, CCR:5, EE:325, NR3D:0, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Capture( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2000 )
IDX_SET( OBC:61, BPC:92, NR1:86, CFA:306, GGM:0, ANR:366, CCR:6, EE:326, NR3D:0, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Capture( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2400 )
IDX_SET( OBC:61, BPC:92, NR1:86, CFA:307, GGM:0, ANR:367, CCR:7, EE:327, NR3D:0, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Capture( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2800 )
IDX_SET( OBC:61, BPC:92, NR1:86, CFA:308, GGM:0, ANR:368, CCR:8, EE:328, NR3D:0, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Capture( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_3200 )
IDX_SET( OBC:61, BPC:92, NR1:86, CFA:309, GGM:0, ANR:369, CCR:9, EE:329, NR3D:0, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_NORMAL)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_ACTION)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_NIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_THEATRE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_BEACH)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_SNOW)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_SUNSET)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_FIREWORKS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_SPORTS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_PARTY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_HDR)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_BARCODE)

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Capture> <Sensor Mode: Custom2>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_DISABLED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Capture( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_100 )
IDX_SET( OBC:62, BPC:93, NR1:87, CFA:310, GGM:0, ANR:370, CCR:0, EE:330, NR3D:0, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Capture( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_200 )
IDX_SET( OBC:62, BPC:94, NR1:88, CFA:311, GGM:0, ANR:371, CCR:1, EE:331, NR3D:0, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Capture( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_400 )
IDX_SET( OBC:62, BPC:94, NR1:88, CFA:312, GGM:0, ANR:372, CCR:2, EE:332, NR3D:0, MFB:0, LCE:0);
// ISO 8004
IDX_MODE_Capture( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_800 )
IDX_SET( OBC:63, BPC:95, NR1:89, CFA:313, GGM:0, ANR:373, CCR:3, EE:333, NR3D:0, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Capture( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1200 )
IDX_SET( OBC:63, BPC:95, NR1:89, CFA:314, GGM:0, ANR:374, CCR:4, EE:334, NR3D:0, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Capture( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1600 )
IDX_SET( OBC:63, BPC:95, NR1:89, CFA:315, GGM:0, ANR:375, CCR:5, EE:335, NR3D:0, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Capture( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2000 )
IDX_SET( OBC:63, BPC:95, NR1:89, CFA:316, GGM:0, ANR:376, CCR:6, EE:336, NR3D:0, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Capture( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2400 )
IDX_SET( OBC:63, BPC:95, NR1:89, CFA:317, GGM:0, ANR:377, CCR:7, EE:337, NR3D:0, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Capture( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2800 )
IDX_SET( OBC:63, BPC:95, NR1:89, CFA:318, GGM:0, ANR:378, CCR:8, EE:338, NR3D:0, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Capture( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_3200 )
IDX_SET( OBC:63, BPC:95, NR1:89, CFA:319, GGM:0, ANR:379, CCR:9, EE:339, NR3D:0, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_NORMAL)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_ACTION)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_NIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_THEATRE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_BEACH)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_SNOW)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_SUNSET)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_FIREWORKS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_SPORTS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_PARTY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_HDR)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_BARCODE)

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Capture> <Sensor Mode: Custom3>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_DISABLED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Capture( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_100 )
IDX_SET( OBC:64, BPC:96, NR1:90, CFA:320, GGM:0, ANR:380, CCR:0, EE:340, NR3D:0, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Capture( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_200 )
IDX_SET( OBC:64, BPC:97, NR1:91, CFA:321, GGM:0, ANR:381, CCR:1, EE:341, NR3D:0, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Capture( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_400 )
IDX_SET( OBC:64, BPC:97, NR1:91, CFA:322, GGM:0, ANR:382, CCR:2, EE:342, NR3D:0, MFB:0, LCE:0);
// ISO 8004
IDX_MODE_Capture( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_800 )
IDX_SET( OBC:65, BPC:98, NR1:92, CFA:323, GGM:0, ANR:383, CCR:3, EE:343, NR3D:0, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Capture( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1200 )
IDX_SET( OBC:65, BPC:98, NR1:92, CFA:324, GGM:0, ANR:384, CCR:4, EE:344, NR3D:0, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Capture( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1600 )
IDX_SET( OBC:65, BPC:98, NR1:92, CFA:325, GGM:0, ANR:385, CCR:5, EE:345, NR3D:0, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Capture( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2000 )
IDX_SET( OBC:65, BPC:98, NR1:92, CFA:326, GGM:0, ANR:386, CCR:6, EE:346, NR3D:0, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Capture( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2400 )
IDX_SET( OBC:65, BPC:98, NR1:92, CFA:327, GGM:0, ANR:387, CCR:7, EE:347, NR3D:0, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Capture( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2800 )
IDX_SET( OBC:65, BPC:98, NR1:92, CFA:328, GGM:0, ANR:388, CCR:8, EE:348, NR3D:0, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Capture( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_3200 )
IDX_SET( OBC:65, BPC:98, NR1:92, CFA:329, GGM:0, ANR:389, CCR:9, EE:349, NR3D:0, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_NORMAL)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_ACTION)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_NIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_THEATRE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_BEACH)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_SNOW)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_SUNSET)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_FIREWORKS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_SPORTS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_PARTY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_HDR)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_BARCODE)

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Capture> <Sensor Mode: Custom4>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_DISABLED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Capture( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_100 )
IDX_SET( OBC:66,  BPC:99, NR1:93, CFA:330, GGM:0, ANR:390, CCR:0, EE:350, NR3D:0, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Capture( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_200 )
IDX_SET( OBC:66, BPC:100, NR1:94, CFA:331, GGM:0, ANR:391, CCR:1, EE:351, NR3D:0, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Capture( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_400 )
IDX_SET( OBC:66, BPC:100, NR1:94, CFA:332, GGM:0, ANR:392, CCR:2, EE:352, NR3D:0, MFB:0, LCE:0);
// ISO 8004
IDX_MODE_Capture( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_800 )
IDX_SET( OBC:67, BPC:101, NR1:95, CFA:333, GGM:0, ANR:393, CCR:3, EE:353, NR3D:0, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Capture( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1200 )
IDX_SET( OBC:67, BPC:101, NR1:95, CFA:334, GGM:0, ANR:394, CCR:4, EE:354, NR3D:0, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Capture( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1600 )
IDX_SET( OBC:67, BPC:101, NR1:95, CFA:335, GGM:0, ANR:395, CCR:5, EE:355, NR3D:0, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Capture( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2000 )
IDX_SET( OBC:67, BPC:101, NR1:95, CFA:336, GGM:0, ANR:396, CCR:6, EE:356, NR3D:0, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Capture( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2400 )
IDX_SET( OBC:67, BPC:101, NR1:95, CFA:337, GGM:0, ANR:397, CCR:7, EE:357, NR3D:0, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Capture( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2800 )
IDX_SET( OBC:67, BPC:101, NR1:95, CFA:338, GGM:0, ANR:398, CCR:8, EE:358, NR3D:0, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Capture( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_3200 )
IDX_SET( OBC:67, BPC:101, NR1:95, CFA:339, GGM:0, ANR:399, CCR:9, EE:359, NR3D:0, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_NORMAL)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_ACTION)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_NIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_THEATRE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_BEACH)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_SNOW)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_SUNSET)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_FIREWORKS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_SPORTS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_PARTY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_HDR)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_BARCODE)

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Capture> <Sensor Mode: Custom5>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_DISABLED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Capture( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_100 )
IDX_SET( OBC:68, BPC:102, NR1:96, CFA:340, GGM:0, ANR:400, CCR:0, EE:360, NR3D:0, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Capture( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_200 )
IDX_SET( OBC:68, BPC:103, NR1:97, CFA:341, GGM:0, ANR:401, CCR:1, EE:361, NR3D:0, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Capture( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_400 )
IDX_SET( OBC:68, BPC:103, NR1:97, CFA:342, GGM:0, ANR:402, CCR:2, EE:362, NR3D:0, MFB:0, LCE:0);
// ISO 8004
IDX_MODE_Capture( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_800 )
IDX_SET( OBC:69, BPC:104, NR1:98, CFA:343, GGM:0, ANR:403, CCR:3, EE:363, NR3D:0, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Capture( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1200 )
IDX_SET( OBC:69, BPC:104, NR1:98, CFA:344, GGM:0, ANR:404, CCR:4, EE:364, NR3D:0, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Capture( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1600 )
IDX_SET( OBC:69, BPC:104, NR1:98, CFA:345, GGM:0, ANR:405, CCR:5, EE:365, NR3D:0, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Capture( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2000 )
IDX_SET( OBC:69, BPC:104, NR1:98, CFA:346, GGM:0, ANR:406, CCR:6, EE:366, NR3D:0, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Capture( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2400 )
IDX_SET( OBC:69, BPC:104, NR1:98, CFA:347, GGM:0, ANR:407, CCR:7, EE:367, NR3D:0, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Capture( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2800 )
IDX_SET( OBC:69, BPC:104, NR1:98, CFA:348, GGM:0, ANR:408, CCR:8, EE:368, NR3D:0, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Capture( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_3200 )
IDX_SET( OBC:69, BPC:104, NR1:98, CFA:349, GGM:0, ANR:409, CCR:9, EE:369, NR3D:0, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_NORMAL)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_ACTION)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_NIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_THEATRE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_BEACH)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_SNOW)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_SUNSET)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_FIREWORKS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_SPORTS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_PARTY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_HDR)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_BARCODE)


#endif //  _CFG_ISP_TUNING_IDX_CAPTURE_H_

