/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 */
/* MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */

/********************************************************************************************
 *     LEGAL DISCLAIMER
 *
 *     (Header of MediaTek Software/Firmware Release or Documentation)
 *
 *     BY OPENING OR USING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 *     THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE") RECEIVED
 *     FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON AN "AS-IS" BASIS
 *     ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES, EXPRESS OR IMPLIED,
 *     INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR
 *     A PARTICULAR PURPOSE OR NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY
 *     WHATSOEVER WITH RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
 *     INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK
 *     ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
 *     NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S SPECIFICATION
 *     OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
 *
 *     BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE LIABILITY WITH
 *     RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE, AT MEDIATEK'S OPTION,
TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE
 *     FEES OR SERVICE CHARGE PAID BY BUYER TO MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 *     THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE WITH THE LAWS
 *     OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF LAWS PRINCIPLES.
 ************************************************************************************************/
#ifndef _CFG_ISP_TUNING_IDX_VIDEO_H_
#define _CFG_ISP_TUNING_IDX_VIDEO_H_

#include <mtkcam/metadata/client/mtk_metadata_tag.h>

#define VIDEO_SCENE_MODE_CONFIG(sensor, scene)\
    IDX_MODE_Video(sensor, scene, eIDX_ISO_100)\
    IdxSet<EIspProfile_Video, sensor, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_100>::idx;\
    IDX_MODE_Video(sensor, scene, eIDX_ISO_200)\
    IdxSet<EIspProfile_Video, sensor, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_200>::idx;\
    IDX_MODE_Video(sensor, scene, eIDX_ISO_400)\
    IdxSet<EIspProfile_Video, sensor, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_400>::idx;\
    IDX_MODE_Video(sensor, scene, eIDX_ISO_800)\
    IdxSet<EIspProfile_Video, sensor, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_800>::idx;\
    IDX_MODE_Video(sensor, scene, eIDX_ISO_1200)\
    IdxSet<EIspProfile_Video, sensor, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1200>::idx;\
    IDX_MODE_Video(sensor, scene, eIDX_ISO_1600)\
    IdxSet<EIspProfile_Video, sensor, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1600>::idx;\
    IDX_MODE_Video(sensor, scene, eIDX_ISO_2000)\
    IdxSet<EIspProfile_Video, sensor, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2000>::idx;\
    IDX_MODE_Video(sensor, scene, eIDX_ISO_2400)\
    IdxSet<EIspProfile_Video, sensor, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2400>::idx;\
    IDX_MODE_Video(sensor, scene, eIDX_ISO_2800)\
    IdxSet<EIspProfile_Video, sensor, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2800>::idx;\
    IDX_MODE_Video(sensor, scene, eIDX_ISO_3200)\
    IdxSet<EIspProfile_Video, sensor, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_3200>::idx;\

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Video> <Sensor Mode: Preview>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_DISABLED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Video( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_100 )
IDX_SET( OBC:10, BPC:15, NR1:15, CFA:50, GGM:0, ANR:50, CCR:0, EE:50, NR3D:50, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Video( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_200 )
IDX_SET( OBC:10, BPC:16, NR1:16, CFA:51, GGM:0, ANR:51, CCR:1, EE:51, NR3D:51, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Video( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_400 )
IDX_SET( OBC:10, BPC:16, NR1:16, CFA:52, GGM:0, ANR:52, CCR:2, EE:52, NR3D:52, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Video( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_800 )
IDX_SET( OBC:11, BPC:17, NR1:17, CFA:53, GGM:0, ANR:53, CCR:3, EE:53, NR3D:53, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Video( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1200 )
IDX_SET( OBC:11, BPC:17, NR1:17, CFA:54, GGM:0, ANR:54, CCR:4, EE:54, NR3D:54, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Video( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1600 )
IDX_SET( OBC:11, BPC:17, NR1:17, CFA:55, GGM:0, ANR:55, CCR:5, EE:55, NR3D:55, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Video( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2000 )
IDX_SET( OBC:11, BPC:17, NR1:17, CFA:56, GGM:0, ANR:56, CCR:6, EE:56, NR3D:56, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Video( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2400 )
IDX_SET( OBC:11, BPC:17, NR1:17, CFA:57, GGM:0, ANR:57, CCR:7, EE:57, NR3D:57, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Video( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2800 )
IDX_SET( OBC:11, BPC:17, NR1:17, CFA:58, GGM:0, ANR:58, CCR:8, EE:58, NR3D:58, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Video( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_3200 )
IDX_SET( OBC:11, BPC:17, NR1:17, CFA:59, GGM:0, ANR:59, CCR:9, EE:59, NR3D:59, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_NORMAL)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_ACTION)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_PORTRAIT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_NIGHT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_THEATRE)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_BEACH)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_SNOW)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_SUNSET)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_FIREWORKS)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_SPORTS)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_PARTY)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_HDR)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_BARCODE)


//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Video> <Sensor Mode: Capture>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_DISABLED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Video( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_100 )
IDX_SET( OBC:12, BPC:18, NR1:18, CFA:60, GGM:0, ANR:60, CCR:0, EE:60, NR3D:60, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Video( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_200 )
IDX_SET( OBC:12, BPC:19, NR1:19, CFA:61, GGM:0, ANR:61, CCR:1, EE:61, NR3D:61, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Video( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_400 )
IDX_SET( OBC:12, BPC:19, NR1:19, CFA:62, GGM:0, ANR:62, CCR:2, EE:62, NR3D:62, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Video( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_800 )
IDX_SET( OBC:13, BPC:20, NR1:20, CFA:63, GGM:0, ANR:63, CCR:3, EE:63, NR3D:63, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Video( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1200 )
IDX_SET( OBC:13, BPC:20, NR1:20, CFA:64, GGM:0, ANR:64, CCR:4, EE:64, NR3D:64, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Video( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1600 )
IDX_SET( OBC:13, BPC:20, NR1:20, CFA:65, GGM:0, ANR:65, CCR:5, EE:65, NR3D:65, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Video( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2000 )
IDX_SET( OBC:13, BPC:20, NR1:20, CFA:66, GGM:0, ANR:66, CCR:6, EE:66, NR3D:66, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Video( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2400 )
IDX_SET( OBC:13, BPC:20, NR1:20, CFA:67, GGM:0, ANR:67, CCR:7, EE:67, NR3D:67, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Video( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2800 )
IDX_SET( OBC:13, BPC:20, NR1:20, CFA:68, GGM:0, ANR:68, CCR:8, EE:68, NR3D:68, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Video( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_3200 )
IDX_SET( OBC:13, BPC:20, NR1:20, CFA:69, GGM:0, ANR:69, CCR:9, EE:69, NR3D:69, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_NORMAL)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_ACTION)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_PORTRAIT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_NIGHT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_THEATRE)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_BEACH)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_SNOW)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_SUNSET)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_FIREWORKS)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_SPORTS)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_PARTY)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_HDR)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_BARCODE)

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Video> <Sensor Mode: Video>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_DISABLED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Video( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_100 )
IDX_SET( OBC:14, BPC:21, NR1:21, CFA:70, GGM:0, ANR:70, CCR:0, EE:70, NR3D:70, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Video( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_200 )
IDX_SET( OBC:14, BPC:22, NR1:22, CFA:71, GGM:0, ANR:71, CCR:1, EE:71, NR3D:71, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Video( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_400 )
IDX_SET( OBC:14, BPC:22, NR1:22, CFA:72, GGM:0, ANR:72, CCR:2, EE:72, NR3D:72, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Video( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_800 )
IDX_SET( OBC:15, BPC:23, NR1:23, CFA:73, GGM:0, ANR:73, CCR:3, EE:73, NR3D:73, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Video( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1200 )
IDX_SET( OBC:15, BPC:23, NR1:23, CFA:74, GGM:0, ANR:74, CCR:4, EE:74, NR3D:74, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Video( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1600 )
IDX_SET( OBC:15, BPC:23, NR1:23, CFA:75, GGM:0, ANR:75, CCR:5, EE:75, NR3D:75, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Video( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2000 )
IDX_SET( OBC:15, BPC:23, NR1:23, CFA:76, GGM:0, ANR:76, CCR:6, EE:76, NR3D:76, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Video( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2400 )
IDX_SET( OBC:15, BPC:23, NR1:23, CFA:77, GGM:0, ANR:77, CCR:7, EE:77, NR3D:77, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Video( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2800 )
IDX_SET( OBC:15, BPC:23, NR1:23, CFA:78, GGM:0, ANR:78, CCR:8, EE:78, NR3D:78, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Video( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_3200 )
IDX_SET( OBC:15, BPC:23, NR1:23, CFA:79, GGM:0, ANR:79, CCR:9, EE:79, NR3D:79, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_NORMAL)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_ACTION)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_PORTRAIT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_NIGHT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_THEATRE)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_BEACH)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_SNOW)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_SUNSET)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_FIREWORKS)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_SPORTS)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_PARTY)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_HDR)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_BARCODE)

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Video> <Sensor Mode: SimVideo1>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_DISABLED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Video( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_100 )
IDX_SET( OBC:16, BPC:24, NR1:24, CFA:80, GGM:0, ANR:80, CCR:0, EE:80, NR3D:80, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Video( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_200 )
IDX_SET( OBC:16, BPC:25, NR1:25, CFA:81, GGM:0, ANR:81, CCR:1, EE:81, NR3D:81, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Video( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_400 )
IDX_SET( OBC:16, BPC:25, NR1:25, CFA:82, GGM:0, ANR:82, CCR:2, EE:82, NR3D:82, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Video( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_800 )
IDX_SET( OBC:17, BPC:26, NR1:26, CFA:83, GGM:0, ANR:83, CCR:3, EE:83, NR3D:83, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Video( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1200 )
IDX_SET( OBC:17, BPC:26, NR1:26, CFA:84, GGM:0, ANR:84, CCR:4, EE:84, NR3D:84, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Video( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1600 )
IDX_SET( OBC:17, BPC:26, NR1:26, CFA:85, GGM:0, ANR:85, CCR:5, EE:85, NR3D:85, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Video( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2000 )
IDX_SET( OBC:17, BPC:26, NR1:26, CFA:86, GGM:0, ANR:86, CCR:6, EE:86, NR3D:86, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Video( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2400 )
IDX_SET( OBC:17, BPC:26, NR1:26, CFA:87, GGM:0, ANR:87, CCR:7, EE:87, NR3D:87, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Video( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2800 )
IDX_SET( OBC:17, BPC:26, NR1:26, CFA:88, GGM:0, ANR:88, CCR:8, EE:88, NR3D:88, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Video( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_3200 )
IDX_SET( OBC:17, BPC:26, NR1:26, CFA:89, GGM:0, ANR:89, CCR:9, EE:89, NR3D:89, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
VIDEO_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_NORMAL)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_ACTION)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_PORTRAIT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_NIGHT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_THEATRE)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_BEACH)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_SNOW)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_SUNSET)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_FIREWORKS)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_SPORTS)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_PARTY)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_HDR)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_BARCODE)

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Video> <Sensor Mode: SlimVideo2>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_DISABLED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Video( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_100 )
IDX_SET( OBC:18, BPC:27, NR1:27, CFA:90, GGM:0, ANR:90, CCR:0, EE:90, NR3D:90, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Video( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_200 )
IDX_SET( OBC:18, BPC:28, NR1:28, CFA:91, GGM:0, ANR:91, CCR:1, EE:91, NR3D:91, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Video( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_400 )
IDX_SET( OBC:18, BPC:28, NR1:28, CFA:92, GGM:0, ANR:92, CCR:2, EE:92, NR3D:92, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Video( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_800 )
IDX_SET( OBC:19, BPC:29, NR1:29, CFA:93, GGM:0, ANR:93, CCR:3, EE:93, NR3D:93, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Video( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1200 )
IDX_SET( OBC:19, BPC:29, NR1:29, CFA:94, GGM:0, ANR:94, CCR:4, EE:94, NR3D:94, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Video( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1600 )
IDX_SET( OBC:19, BPC:29, NR1:29, CFA:95, GGM:0, ANR:95, CCR:5, EE:95, NR3D:95, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Video( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2000 )
IDX_SET( OBC:19, BPC:29, NR1:29, CFA:96, GGM:0, ANR:96, CCR:6, EE:96, NR3D:96, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Video( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2400 )
IDX_SET( OBC:19, BPC:29, NR1:29, CFA:97, GGM:0, ANR:97, CCR:7, EE:97, NR3D:97, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Video( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2800 )
IDX_SET( OBC:19, BPC:29, NR1:29, CFA:98, GGM:0, ANR:98, CCR:8, EE:98, NR3D:98, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Video( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_3200 )
IDX_SET( OBC:19, BPC:29, NR1:29, CFA:99, GGM:0, ANR:99, CCR:9, EE:99, NR3D:99, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
VIDEO_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_NORMAL)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_ACTION)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_PORTRAIT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_NIGHT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_THEATRE)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_BEACH)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_SNOW)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_SUNSET)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_FIREWORKS)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_SPORTS)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_PARTY)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_HDR)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_BARCODE)

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Video> <Sensor Mode: Custom1>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_DISABLED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Video( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_100 )
IDX_SET( OBC:50, BPC:75, NR1:69, CFA:250, GGM:0, ANR:310, CCR:0, EE:270, NR3D:190, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Video( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_200 )
IDX_SET( OBC:50, BPC:76, NR1:70, CFA:251, GGM:0, ANR:311, CCR:1, EE:271, NR3D:191, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Video( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_400 )
IDX_SET( OBC:50, BPC:76, NR1:70, CFA:252, GGM:0, ANR:312, CCR:2, EE:272, NR3D:192, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Video( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_800 )
IDX_SET( OBC:51, BPC:77, NR1:71, CFA:253, GGM:0, ANR:313, CCR:3, EE:273, NR3D:193, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Video( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1200 )
IDX_SET( OBC:51, BPC:77, NR1:71, CFA:254, GGM:0, ANR:314, CCR:4, EE:274, NR3D:194, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Video( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1600 )
IDX_SET( OBC:51, BPC:77, NR1:71, CFA:255, GGM:0, ANR:315, CCR:5, EE:275, NR3D:195, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Video( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2000 )
IDX_SET( OBC:51, BPC:77, NR1:71, CFA:256, GGM:0, ANR:316, CCR:6, EE:276, NR3D:196, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Video( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2400 )
IDX_SET( OBC:51, BPC:77, NR1:71, CFA:257, GGM:0, ANR:317, CCR:7, EE:277, NR3D:197, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Video( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2800 )
IDX_SET( OBC:51, BPC:77, NR1:71, CFA:258, GGM:0, ANR:318, CCR:8, EE:278, NR3D:198, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Video( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_3200 )
IDX_SET( OBC:51, BPC:77, NR1:71, CFA:259, GGM:0, ANR:319, CCR:9, EE:279, NR3D:199, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_NORMAL)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_ACTION)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_PORTRAIT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_NIGHT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_THEATRE)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_BEACH)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_SNOW)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_SUNSET)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_FIREWORKS)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_SPORTS)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_PARTY)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_HDR)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_BARCODE)

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Video> <Sensor Mode: Custom2>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_DISABLED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Video( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_100 )
IDX_SET( OBC:52, BPC:78, NR1:72, CFA:260, GGM:0, ANR:320, CCR:0, EE:280, NR3D:200, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Video( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_200 )
IDX_SET( OBC:52, BPC:79, NR1:73, CFA:261, GGM:0, ANR:321, CCR:1, EE:281, NR3D:201, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Video( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_400 )
IDX_SET( OBC:52, BPC:79, NR1:73, CFA:262, GGM:0, ANR:322, CCR:2, EE:282, NR3D:202, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Video( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_800 )
IDX_SET( OBC:53, BPC:80, NR1:74, CFA:263, GGM:0, ANR:323, CCR:3, EE:283, NR3D:203, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Video( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1200 )
IDX_SET( OBC:53, BPC:80, NR1:74, CFA:264, GGM:0, ANR:324, CCR:4, EE:284, NR3D:204, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Video( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1600 )
IDX_SET( OBC:53, BPC:80, NR1:74, CFA:265, GGM:0, ANR:325, CCR:5, EE:285, NR3D:205, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Video( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2000 )
IDX_SET( OBC:53, BPC:80, NR1:74, CFA:266, GGM:0, ANR:326, CCR:6, EE:286, NR3D:206, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Video( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2400 )
IDX_SET( OBC:53, BPC:80, NR1:74, CFA:267, GGM:0, ANR:327, CCR:7, EE:287, NR3D:207, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Video( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2800 )
IDX_SET( OBC:53, BPC:80, NR1:74, CFA:268, GGM:0, ANR:328, CCR:8, EE:288, NR3D:208, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Video( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_3200 )
IDX_SET( OBC:53, BPC:80, NR1:74, CFA:269, GGM:0, ANR:329, CCR:9, EE:289, NR3D:209, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_NORMAL)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_ACTION)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_PORTRAIT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_NIGHT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_THEATRE)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_BEACH)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_SNOW)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_SUNSET)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_FIREWORKS)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_SPORTS)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_PARTY)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_HDR)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_BARCODE)

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Video> <Sensor Mode: Custom3>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_DISABLED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Video( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_100 )
IDX_SET( OBC:54, BPC:81, NR1:75, CFA:270, GGM:0, ANR:330, CCR:0, EE:290, NR3D:210, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Video( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_200 )
IDX_SET( OBC:54, BPC:82, NR1:76, CFA:271, GGM:0, ANR:331, CCR:1, EE:291, NR3D:211, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Video( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_400 )
IDX_SET( OBC:54, BPC:82, NR1:76, CFA:272, GGM:0, ANR:332, CCR:2, EE:292, NR3D:212, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Video( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_800 )
IDX_SET( OBC:55, BPC:83, NR1:77, CFA:273, GGM:0, ANR:333, CCR:3, EE:293, NR3D:213, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Video( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1200 )
IDX_SET( OBC:55, BPC:83, NR1:77, CFA:274, GGM:0, ANR:334, CCR:4, EE:294, NR3D:214, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Video( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1600 )
IDX_SET( OBC:55, BPC:83, NR1:77, CFA:275, GGM:0, ANR:335, CCR:5, EE:295, NR3D:215, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Video( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2000 )
IDX_SET( OBC:55, BPC:83, NR1:77, CFA:276, GGM:0, ANR:336, CCR:6, EE:296, NR3D:216, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Video( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2400 )
IDX_SET( OBC:55, BPC:83, NR1:77, CFA:277, GGM:0, ANR:337, CCR:7, EE:297, NR3D:217, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Video( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2800 )
IDX_SET( OBC:55, BPC:83, NR1:77, CFA:278, GGM:0, ANR:338, CCR:8, EE:298, NR3D:218, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Video( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_3200 )
IDX_SET( OBC:55, BPC:83, NR1:77, CFA:279, GGM:0, ANR:339, CCR:9, EE:299, NR3D:219, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_NORMAL)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_ACTION)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_PORTRAIT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_NIGHT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_THEATRE)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_BEACH)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_SNOW)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_SUNSET)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_FIREWORKS)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_SPORTS)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_PARTY)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_HDR)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_BARCODE)

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Video> <Sensor Mode: Custom4>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_DISABLED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Video( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_100 )
IDX_SET( OBC:56, BPC:84, NR1:78, CFA:280, GGM:0, ANR:340, CCR:0, EE:300, NR3D:220, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Video( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_200 )
IDX_SET( OBC:56, BPC:85, NR1:79, CFA:281, GGM:0, ANR:341, CCR:1, EE:301, NR3D:221, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Video( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_400 )
IDX_SET( OBC:56, BPC:85, NR1:79, CFA:282, GGM:0, ANR:342, CCR:2, EE:302, NR3D:222, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Video( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_800 )
IDX_SET( OBC:57, BPC:86, NR1:80, CFA:283, GGM:0, ANR:343, CCR:3, EE:303, NR3D:223, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Video( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1200 )
IDX_SET( OBC:57, BPC:86, NR1:80, CFA:284, GGM:0, ANR:344, CCR:4, EE:304, NR3D:224, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Video( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1600 )
IDX_SET( OBC:57, BPC:86, NR1:80, CFA:285, GGM:0, ANR:345, CCR:5, EE:305, NR3D:225, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Video( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2000 )
IDX_SET( OBC:57, BPC:86, NR1:80, CFA:286, GGM:0, ANR:346, CCR:6, EE:306, NR3D:226, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Video( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2400 )
IDX_SET( OBC:57, BPC:86, NR1:80, CFA:287, GGM:0, ANR:347, CCR:7, EE:307, NR3D:227, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Video( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2800 )
IDX_SET( OBC:57, BPC:86, NR1:80, CFA:288, GGM:0, ANR:348, CCR:8, EE:308, NR3D:228, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Video( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_3200 )
IDX_SET( OBC:57, BPC:86, NR1:80, CFA:289, GGM:0, ANR:349, CCR:9, EE:309, NR3D:229, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_NORMAL)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_ACTION)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_PORTRAIT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_NIGHT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_THEATRE)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_BEACH)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_SNOW)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_SUNSET)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_FIREWORKS)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_SPORTS)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_PARTY)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_HDR)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_BARCODE)

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Video> <Sensor Mode: Custom5>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_DISABLED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Video( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_100 )
IDX_SET( OBC:58, BPC:87, NR1:81, CFA:290, GGM:0, ANR:350, CCR:0, EE:310, NR3D:230, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Video( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_200 )
IDX_SET( OBC:58, BPC:88, NR1:82, CFA:291, GGM:0, ANR:351, CCR:1, EE:311, NR3D:231, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Video( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_400 )
IDX_SET( OBC:58, BPC:88, NR1:82, CFA:292, GGM:0, ANR:352, CCR:2, EE:312, NR3D:232, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Video( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_800 )
IDX_SET( OBC:59, BPC:89, NR1:83, CFA:293, GGM:0, ANR:353, CCR:3, EE:313, NR3D:233, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Video( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1200 )
IDX_SET( OBC:59, BPC:89, NR1:83, CFA:294, GGM:0, ANR:354, CCR:4, EE:314, NR3D:234, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Video( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_1600 )
IDX_SET( OBC:59, BPC:89, NR1:83, CFA:295, GGM:0, ANR:355, CCR:5, EE:315, NR3D:235, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Video( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2000 )
IDX_SET( OBC:59, BPC:89, NR1:83, CFA:296, GGM:0, ANR:356, CCR:6, EE:316, NR3D:236, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Video( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2400 )
IDX_SET( OBC:59, BPC:89, NR1:83, CFA:297, GGM:0, ANR:357, CCR:7, EE:317, NR3D:237, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Video( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_2800 )
IDX_SET( OBC:59, BPC:89, NR1:83, CFA:298, GGM:0, ANR:358, CCR:8, EE:318, NR3D:238, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Video( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_DISABLED, eIDX_ISO_3200 )
IDX_SET( OBC:59, BPC:89, NR1:83, CFA:299, GGM:0, ANR:359, CCR:9, EE:319, NR3D:239, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_NORMAL)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_ACTION)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_PORTRAIT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_NIGHT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_THEATRE)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_BEACH)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_SNOW)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_SUNSET)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_FIREWORKS)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_SPORTS)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_PARTY)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_HDR)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
VIDEO_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_BARCODE)


#endif //  _CFG_ISP_TUNING_IDX_VIDEO_H_

