/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mtk_offlinek_MainActivity */

#ifndef _Included_com_mtk_offlinek_MainActivity
#define _Included_com_mtk_offlinek_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mtk_offlinek_MainActivity
 * Method:    getHString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mtk_offlinek_MainActivity_getHString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
