/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mtk_offlinek_NativeLoader */

#ifndef _Included_com_mtk_offlinek_NativeLoader
#define _Included_com_mtk_offlinek_NativeLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mtk_offlinek_NativeLoader
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mtk_offlinek_NativeLoader_init
  (JNIEnv *, jobject);

/*
 * Class:     com_mtk_offlinek_NativeLoader
 * Method:    getHString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mtk_offlinek_NativeLoader_getHString
  (JNIEnv *, jobject);

/*
 * Class:     com_mtk_offlinek_NativeLoader
 * Method:    doETT
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mtk_offlinek_NativeLoader_doETT
  (JNIEnv *, jobject);

/*
 * Class:     com_mtk_offlinek_NativeLoader
 * Method:    setRecordItem
 * Signature: (Lcom/mtk/offlinek/fragment/RecordItem;)I
 */
JNIEXPORT jint JNICALL Java_com_mtk_offlinek_NativeLoader_setRecordItem
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mtk_offlinek_NativeLoader
 * Method:    switchVoltage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mtk_offlinek_NativeLoader_switchVoltage
  (JNIEnv *, jobject);

/*
 * Class:     com_mtk_offlinek_NativeLoader
 * Method:    getProgress
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mtk_offlinek_NativeLoader_getProgress
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
