/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 */
/* MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */

/********************************************************************************************
 *     LEGAL DISCLAIMER
 *
 *     (Header of MediaTek Software/Firmware Release or Documentation)
 *
 *     BY OPENING OR USING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 *     THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE") RECEIVED
 *     FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON AN "AS-IS" BASIS
 *     ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES, EXPRESS OR IMPLIED,
 *     INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR
 *     A PARTICULAR PURPOSE OR NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY
 *     WHATSOEVER WITH RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
 *     INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK
 *     ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
 *     NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S SPECIFICATION
 *     OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
 *
 *     BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE LIABILITY WITH
 *     RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE, AT MEDIATEK'S OPTION,
TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE
 *     FEES OR SERVICE CHARGE PAID BY BUYER TO MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 *     THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE WITH THE LAWS
 *     OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF LAWS PRINCIPLES.
 ************************************************************************************************/
#ifndef _ISP_MGR_AF_STAT_H_
#define _ISP_MGR_AF_STAT_H_

#include <aaa_buf_mgr.h>
#include <af_param.h>
#include <isp_mgr.h>

using namespace NS3Av3;

namespace NSIspTuningv3
{
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
//  AF statistics config
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
typedef class ISP_MGR_AF_STAT_CONFIG : public ISP_MGR_BASE_T
{
    typedef ISP_MGR_AF_STAT_CONFIG    MyType;
private:
    MUINT32 m_u4StartAddr;

    enum
    {
        ERegInfo_CAM_AFO_XSIZE,
        ERegInfo_CAM_AFO_YSIZE,
        ERegInfo_CAM_AFO_STRIDE,
        ERegInfo_CAM_AF_CON,
        ERegInfo_CAM_AF_TH_0,
        ERegInfo_CAM_AF_TH_1,
        ERegInfo_CAM_AF_FLT_1,
        ERegInfo_CAM_AF_FLT_2,
        ERegInfo_CAM_AF_FLT_3,
        ERegInfo_CAM_AF_FLT_4,
        ERegInfo_CAM_AF_FLT_5,
        ERegInfo_CAM_AF_FLT_6,
        ERegInfo_CAM_AF_FLT_7,
        ERegInfo_CAM_AF_FLT_8,
        ERegInfo_CAM_AF_SIZE,
        ERegInfo_CAM_AF_VLD,
        ERegInfo_CAM_AF_BLK_0,
        ERegInfo_CAM_AF_BLK_1,
        ERegInfo_CAM_SGG1_PGN,
        ERegInfo_CAM_SGG1_GMRC_1,
        ERegInfo_CAM_SGG1_GMRC_2,
        ERegInfo_NUM
    };

    RegInfo_T   m_rIspRegInfo[ERegInfo_NUM];

protected:
    ISP_MGR_AF_STAT_CONFIG(ESensorDev_T const eSensorDev)
        : ISP_MGR_BASE_T(m_rIspRegInfo, ERegInfo_NUM, m_u4StartAddr, eSensorDev)
        , m_u4StartAddr(REG_ADDR_P1(CAM_AFO_XSIZE))
    {
        INIT_REG_INFO_ADDR_P1(CAM_AFO_XSIZE);
        INIT_REG_INFO_ADDR_P1(CAM_AFO_YSIZE);
        INIT_REG_INFO_ADDR_P1(CAM_AFO_STRIDE);
        INIT_REG_INFO_ADDR_P1(CAM_AF_CON);
        INIT_REG_INFO_ADDR_P1(CAM_AF_TH_0);
        INIT_REG_INFO_ADDR_P1(CAM_AF_TH_1);
        INIT_REG_INFO_ADDR_P1(CAM_AF_FLT_1);
        INIT_REG_INFO_ADDR_P1(CAM_AF_FLT_2);
        INIT_REG_INFO_ADDR_P1(CAM_AF_FLT_3);
        INIT_REG_INFO_ADDR_P1(CAM_AF_FLT_4);
        INIT_REG_INFO_ADDR_P1(CAM_AF_FLT_5);
        INIT_REG_INFO_ADDR_P1(CAM_AF_FLT_6);
        INIT_REG_INFO_ADDR_P1(CAM_AF_FLT_7);
        INIT_REG_INFO_ADDR_P1(CAM_AF_FLT_8);
        INIT_REG_INFO_ADDR_P1(CAM_AF_SIZE);
        INIT_REG_INFO_ADDR_P1(CAM_AF_VLD);
        INIT_REG_INFO_ADDR_P1(CAM_AF_BLK_0);
        INIT_REG_INFO_ADDR_P1(CAM_AF_BLK_1);
        INIT_REG_INFO_ADDR_P1(CAM_SGG1_PGN);
        INIT_REG_INFO_ADDR_P1(CAM_SGG1_GMRC_1);
        INIT_REG_INFO_ADDR_P1(CAM_SGG1_GMRC_2);
    }

    virtual ~ISP_MGR_AF_STAT_CONFIG() {}

public: ////
    static MyType&  getInstance(ESensorDev_T const eSensorDev);

public: //    Interfaces
  MBOOL config(AF_CONFIG_T &a_sAFConfig);
    MBOOL apply(TuningMgr& rTuning);
} ISP_MGR_AF_STAT_CONFIG_T;

template <ESensorDev_T const eSensorDev>
class ISP_MGR_AF_STAT_CONFIG_DEV : public ISP_MGR_AF_STAT_CONFIG_T
{
public:
    static
    ISP_MGR_AF_STAT_CONFIG_T&
    getInstance()
    {
        static ISP_MGR_AF_STAT_CONFIG_DEV<eSensorDev> singleton;
        return singleton;
    }
    virtual MVOID destroyInstance() {}

    ISP_MGR_AF_STAT_CONFIG_DEV()
        : ISP_MGR_AF_STAT_CONFIG_T(eSensorDev)
    {}

    virtual ~ISP_MGR_AF_STAT_CONFIG_DEV() {}

};

}
#endif
