#ifndef SIMMELOCK_PIC_H
#define SIMMELOCK_PIC_H 1

#define COMMAND_SEPERATOR_LENGTH    1
#define COMMAND_SIM_ID_LENGTH       1
#define COMMAND_RESULT_CODE_LENGTH  15

enum ModemRequest
{
    MODEM_REQUEST_GET_SHARED_KEY = 1,
    MODEM_REQUEST_UPDATE_SIMLOCK_SETTINGS = 2,
    MODEM_REQUEST_GET_SIMLOCK_SETTINGS_INFO = 3,
    MODEM_REQUEST_RESET_SIMLOCK_SETTINGS = 4,
    MODEM_REQUEST_GET_MODEM_STATUS = 5
};

enum ModeomStatus
{
    MODEM_STATUS_REBOOT_REQUEST = 1,
    MODEM_STATUS_OK = 0,
    MODEM_STATUS_CONNECTION_FAILED = -1,
    MODEM_STATUS_UNSUPPORTED_COMMAND = -2,
    MODEM_STATUS_VERIFICATION_FAILED = -3,
    MODEM_STATUS_BUFFER_TOO_SHORT = -4,
    MODEM_STATUS_FAILURE_TO_HANDLE_MESSAGE = -5
};

#endif /*SIMMELOCK_PIC_H*/