
package com.mediatek.ims;

public interface VaConstants {

    /* system */
    // MSG_ID_WRAP_IMSPA_START = 900000;
    int MSG_ID_WRAP_IMSPA_IMSM_INFORMATION_IND = 900001;
    int MSG_ID_WRAP_IMSM_IMSPA_INFORMATION_REQ = 900002;
    int MSG_ID_IMS_ENABLE_IND = 900003; // MSG_ID_WRAP_IMSPA_IMSM_ENABLE_IND
    int MSG_ID_IMS_DISABLE_IND = 900004; // MSG_ID_WRAP_IMSPA_IMSM_DISABLE_IND,
    // MSG_ID_WRAP_IMSM_IMSPA_STATE_IND,
    int MSG_ID_WRAP_IMSM_IMSPA_PDN_ACT_REQ = 900008;
    int MSG_ID_WRAP_IMSPA_IMSM_PDN_ACT_ACK_RESP = 900009;
    int MSG_ID_WRAP_IMSPA_IMSM_PDN_ACT_REJ_RESP = 900010;
    int MSG_ID_WRAP_IMSM_IMSPA_PDN_DEACT_REQ = 900011;
    int MSG_ID_WRAP_IMSPA_IMSM_PDN_DEACT_ACK_RESP = 900012;
    int MSG_ID_WRAP_IMSPA_IMSM_PDN_DEACT_REJ_RESP = 900013;
    int MSG_ID_WRAP_IMSPA_IMSM_PDN_DEACT_IND = 900014;

    /* timer */
    // MSG_ID_WRAP_TIMER_START = 900200
    int MSG_ID_REQUEST_TIMER_CREATE = 900201; // MSG_ID_WRAP_TIMER_START_REQ
    int MSG_ID_REQUEST_TIMER_CANCEL = 900202; // MSG_ID_WRAP_TIMER_CANCEL_REQ
    int MSG_ID_NOTIFY_TIMER_EXPIRY = 900203; // MSG_ID_WRAP_IMSPA_IMSM_TIMER_TIMEOUT_IND

    /* others */
    // MSG_ID_WRAP_OTHERS_START = 900400
    int MSG_ID_NOTIFY_XUI_IND = 900401; // MSG_ID_WRAP_IMSM_IMSPA_XUI_REQ
    int MSG_ID_NOTIFY_SS_PROGRESS_INDICATION = 900402; // MSG_ID_WRAP_IMSM_IMSPA_SS_PROGRESS_REQ
    int MSG_ID_REQUEST_PCSCF_DISCOVERY = 900403; // MSG_ID_WRAP_IMSM_IMSPA_PCSCF_REQ,
    int MSG_ID_RESPONSE_PCSCF_DISCOVERY = 900404; // MSG_ID_WRAP_IMSPA_PCSCF_ACK_RESP,
    int MSG_ID_REJECT_PCSCF_DISCOVERY = 900405; // MSG_ID_WRAP_IMSPA_IMSM_PCSCF_REJ_RESP,

    /* IMSA internal used */
    int MSG_ID_IMSA_ENABLE_IMS_SEND_APN_IND = 900501;
}
