#Auto generated by sub release
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MULTILIB := both
LOCAL_MODULE := liba3m
LOCAL_MODULE_TARGET_ARCH := arm arm64
my_src_arch := $(call get-prebuilt-src-arch,$(LOCAL_MODULE_TARGET_ARCH))
LOCAL_SRC_FILES_arm := lib/arm/liba3m.so
LOCAL_SRC_FILES_arm64 := lib/arm64/liba3m.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_SHARED_LIBRARIES := libEGL libGLESv2 libandroid libcutils liblog libstdc++ libutils libmtk_drvb
include $(BUILD_PREBUILT)
