/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein is
 * confidential and proprietary to MediaTek Inc. and/or its licensors. Without
 * the prior written permission of MediaTek inc. and/or its licensors, any
 * reproduction, modification, use or disclosure of MediaTek Software, and
 * information contained herein, in whole or in part, shall be strictly
 * prohibited.
 *
 * MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER
 * ON AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR
 * NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH
 * RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
 * INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES
 * TO LOOK ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO.
 * RECEIVER EXPRESSLY ACKNOWLEDGES THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO
 * OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES CONTAINED IN MEDIATEK
 * SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE
 * RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S
 * ENTIRE AND CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE
 * RELEASED HEREUNDER WILL BE, AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE
 * MEDIATEK SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE
 * CHARGE PAID BY RECEIVER TO MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek
 * Software") have been modified by MediaTek Inc. All revisions are subject to
 * any receiver's applicable license agreements with MediaTek Inc.
 */

#ifndef _MTK_HARDWARE_INCLUDE_MTKCAM_STATICMETATABLE_H_
#define _MTK_HARDWARE_INCLUDE_MTKCAM_STATICMETATABLE_H_
namespace CONVERTParam
{
#define SCENE_MODE_SIZE     (17)
#define SCENE_MODE_OVERRIDE_SIZE     (SCENE_MODE_SIZE*3)
    static MUINT8 scenModes[SCENE_MODE_SIZE] ={
        MTK_CONTROL_SCENE_MODE_FACE_PRIORITY,
        MTK_CONTROL_SCENE_MODE_ACTION,
        MTK_CONTROL_SCENE_MODE_PORTRAIT,
        MTK_CONTROL_SCENE_MODE_LANDSCAPE,
        MTK_CONTROL_SCENE_MODE_NIGHT,
        MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT,
        MTK_CONTROL_SCENE_MODE_THEATRE,
        MTK_CONTROL_SCENE_MODE_BEACH,
        MTK_CONTROL_SCENE_MODE_SNOW,
        MTK_CONTROL_SCENE_MODE_SUNSET,
        MTK_CONTROL_SCENE_MODE_STEADYPHOTO,
        MTK_CONTROL_SCENE_MODE_FIREWORKS,
        MTK_CONTROL_SCENE_MODE_SPORTS,
        MTK_CONTROL_SCENE_MODE_PARTY,
        MTK_CONTROL_SCENE_MODE_CANDLELIGHT,
        MTK_CONTROL_SCENE_MODE_BARCODE,
        MTK_CONTROL_SCENE_MODE_HIGH_SPEED_VIDEO
    };
    // 17*3
    static MUINT8 overrideValue[SCENE_MODE_OVERRIDE_SIZE] = {
        //MTK_CONTROL_SCENE_MODE_FACE_PRIORITY
        MTK_CONTROL_AE_MODE_OFF,
        MTK_CONTROL_AWB_MODE_AUTO,
        MTK_CONTROL_AF_MODE_CONTINUOUS_PICTURE,
        //MTK_CONTROL_SCENE_MODE_ACTION
        MTK_CONTROL_AE_MODE_ON_AUTO_FLASH,
        MTK_CONTROL_AWB_MODE_AUTO,
        MTK_CONTROL_AF_MODE_CONTINUOUS_PICTURE,
        //MTK_CONTROL_SCENE_MODE_PORTRAIT
        MTK_CONTROL_AE_MODE_ON_AUTO_FLASH,
        MTK_CONTROL_AWB_MODE_AUTO,
        MTK_CONTROL_AF_MODE_CONTINUOUS_PICTURE,
        //MTK_CONTROL_SCENE_MODE_LANDSCAPE
        MTK_CONTROL_AE_MODE_ON,
        MTK_CONTROL_AWB_MODE_DAYLIGHT,
        MTK_CONTROL_AF_MODE_CONTINUOUS_PICTURE,
        //MTK_CONTROL_SCENE_MODE_NIGHT
        MTK_CONTROL_AE_MODE_ON_AUTO_FLASH,
        MTK_CONTROL_AWB_MODE_AUTO,
        MTK_CONTROL_AF_MODE_CONTINUOUS_PICTURE,
        //MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT
        MTK_CONTROL_AE_MODE_ON_AUTO_FLASH,
        MTK_CONTROL_AWB_MODE_AUTO,
        MTK_CONTROL_AF_MODE_CONTINUOUS_PICTURE,
        //MTK_CONTROL_SCENE_MODE_THEATRE
        MTK_CONTROL_AE_MODE_ON_AUTO_FLASH,
        MTK_CONTROL_AWB_MODE_AUTO,
        MTK_CONTROL_AF_MODE_AUTO,
        //MTK_CONTROL_SCENE_MODE_BEACH
        MTK_CONTROL_AE_MODE_ON_AUTO_FLASH,
        MTK_CONTROL_AWB_MODE_DAYLIGHT,
        MTK_CONTROL_AF_MODE_CONTINUOUS_PICTURE,
        //MTK_CONTROL_SCENE_MODE_SNOW
        MTK_CONTROL_AE_MODE_ON_AUTO_FLASH,
        MTK_CONTROL_AWB_MODE_DAYLIGHT,
        MTK_CONTROL_AF_MODE_CONTINUOUS_PICTURE,
        //MTK_CONTROL_SCENE_MODE_SUNSET
        MTK_CONTROL_AE_MODE_ON,
        MTK_CONTROL_AWB_MODE_DAYLIGHT,
        MTK_CONTROL_AF_MODE_CONTINUOUS_PICTURE,
        //MTK_CONTROL_SCENE_MODE_STEADYPHOTO
        MTK_CONTROL_AE_MODE_ON_AUTO_FLASH,
        MTK_CONTROL_AWB_MODE_AUTO,
        MTK_CONTROL_AF_MODE_CONTINUOUS_PICTURE,
        //MTK_CONTROL_SCENE_MODE_FIREWORKS
        MTK_CONTROL_AE_MODE_OFF,
        MTK_CONTROL_AWB_MODE_DAYLIGHT,
        MTK_CONTROL_AF_MODE_AUTO,
        //MTK_CONTROL_SCENE_MODE_SPORTS
        MTK_CONTROL_AE_MODE_ON_AUTO_FLASH,
        MTK_CONTROL_AWB_MODE_AUTO,
        MTK_CONTROL_AF_MODE_AUTO,
        //MTK_CONTROL_SCENE_MODE_PARTY
        MTK_CONTROL_AE_MODE_ON_AUTO_FLASH,
        MTK_CONTROL_AWB_MODE_AUTO,
        MTK_CONTROL_AF_MODE_CONTINUOUS_PICTURE,
        //MTK_CONTROL_SCENE_MODE_CANDLELIGHT
        MTK_CONTROL_AE_MODE_ON_AUTO_FLASH,
        MTK_CONTROL_AWB_MODE_INCANDESCENT,
        MTK_CONTROL_AF_MODE_CONTINUOUS_PICTURE,
        //MTK_CONTROL_SCENE_MODE_BARCODE
        MTK_CONTROL_AE_MODE_ON_AUTO_FLASH,
        MTK_CONTROL_AWB_MODE_AUTO,
        MTK_CONTROL_AF_MODE_MACRO,
        //MTK_CONTROL_SCENE_MODE_HIGH_SPEED_VIDEO
        MTK_CONTROL_AE_MODE_OFF,
        MTK_CONTROL_AWB_MODE_AUTO,
        MTK_CONTROL_AF_MODE_CONTINUOUS_PICTURE,
    };
};
#endif