# Copyright Statement:
#
# This software/firmware and related documentation ("MediaTek Software") are
# protected under relevant copyright laws. The information contained herein
# is confidential and proprietary to MediaTek Inc. and/or its licensors.
# Without the prior written permission of MediaTek inc. and/or its licensors,
# any reproduction, modification, use or disclosure of MediaTek Software,
# and information contained herein, in whole or in part, shall be strictly prohibited.

# MediaTek Inc. (C) 2010. All rights reserved.
#
# BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
# THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
# RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
# AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
# NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
# SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
# SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
# THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
# THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
# CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
# SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
# STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
# CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
# AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
# OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
# MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
#
# The following software/firmware and/or related documentation ("MediaTek Software")
# have been modified by MediaTek Inc. All revisions are subject to any receiver's
# applicable license agreements with MediaTek Inc.


ifeq ($(TARGET_BOARD_PLATFORM),mt6795)

# MTK_PTGEN_COMMAND is defined in device/mediatek/$(TARGET_BOARD_PLATFORM)/BoardConfig.mk
$(info MTK_PTGEN_COMMAND = $(MTK_PTGEN_COMMAND))

MTK_PTGEN_OTA_SCATTER_PERL := device/mediatek/build/build/tools/ptgen/ota_scatter.pl
MTK_PTGEN_DEP := $(MTK_PTGEN_PERL)
MTK_PTGEN_DEP += $(MTK_PTGEN_XLS)
MTK_PTGEN_DEP += $(MTK_TARGET_PROJECT_FOLDER)/full_$(MTK_TARGET_PROJECT).mk
MTK_PTGEN_DEP += $(MTK_TARGET_PROJECT_FOLDER)/ProjectConfig.mk
MTK_PTGEN_DEP += $(MTK_PROJECT_FOLDER)/BoardConfig.mk
MTK_PTGEN_DEP += device/mediatek/$(TARGET_BOARD_PLATFORM)/BoardConfig.mk
MTK_PTGEN_DEP += device/mediatek/common/BoardConfig.mk

droidcore: $(MTK_PTGEN_OUT)/partition_size.mk $(PRODUCT_OUT)/ota_scatter.txt
ptgen:     $(MTK_PTGEN_OUT)/partition_size.mk $(PRODUCT_OUT)/ota_scatter.txt

$(MTK_PTGEN_OUT)/partition_size.mk: $(wildcard $(MTK_PTGEN_DEP))
	@echo $@: $?
	$(MTK_PTGEN_COMMAND)

$(PRODUCT_OUT)/$(MTK_PTGEN_CHIP)_Android_scatter.txt: $(MTK_PTGEN_OUT)/partition_size.mk
	@echo $@: $?

$(PRODUCT_OUT)/ota_scatter.txt: $(MTK_PTGEN_OTA_SCATTER_PERL) $(PRODUCT_OUT)/$(MTK_PTGEN_CHIP)_Android_scatter.txt
	perl $(MTK_PTGEN_OTA_SCATTER_PERL) $(PRODUCT_OUT)/$(MTK_PTGEN_CHIP)_Android_scatter.txt $(PRODUCT_OUT)/ota_scatter.txt

endif
