#ifndef __CFG_CAMERA_FILE_MAX_SIZE_H__
#define __CFG_CAMERA_FILE_MAX_SIZE_H__

#define MAXIMUM_NVRAM_CAMERA_DEFECT_FILE_SIZE      (5120) //BYTE 81920


#define MAXIMUM_NVRAM_CAMERA_ISP_FILE_SIZE         (143360) // 140K bytes
#define MAXIMUM_NVRAM_CAMERA_3A_FILE_SIZE          (25600) // 25K bytes
#define MAXIMUM_NVRAM_CAMERA_SENSOR_FILE_SIZE      (4096)
#define MAXIMUM_NVRAM_CAMERA_LENS_FILE_SIZE        (16384)
#define MAXIMUM_NVRAM_CAMERA_VERSION_FILE_SIZE		   (80)
#define MAXIMUM_NVRAM_CAMERA_FEATURE_FILE_SIZE      (5120)
#define MAXIMUM_NVRAM_CAMERA_GEOMETRY_FILE_SIZE     (100)

#define MAXIMUM_NVRAM_CAMERA_PLINE_FILE_SIZE     (90000)
#define MAXIMUM_NVRAM_CAMERA_SHADING_FILE_SIZE      (90000) //BYTE 81920--> 16000 for meta tool limitation

#define MAXIMUM_CAMERA_SHADING_SIZE  (1050652)
#define MAXIMUM_CAMERA_PLINE_SIZE  (900000)

#define MAXIMUM_NVRAM_CAMERA_PARA_FILE_SIZE  MAXIMUM_NVRAM_CAMERA_ISP_FILE_SIZE

#endif
